#!/bin/bash
/show/description "pilightCommand Status"
/show/listecho  "PRESS [CTRL-C] to quit" $WARN
/show/listecho "Supervisor status" $OK
supervisorctl status pilightCommand
/show/description "Pilight Command log" $OK
tail -f /var/log/pilightCommand.log
