#!/bin/bash
installer supervisor
cat <<\EOF > /etc/supervisor/conf.d/pilightCommand.conf
[program: pilightCommand]
command=/opt/piget/pilightCommand/pilightCommand
autostart=true
autorestart=true
stdout_logfile=/var/log/pilightCommand.log
redirect_stderr=true
EOF
supervisorctl reread
supervisorctl update


