#!/bin/bash
description "We need pilight to triggers actions with radiocode"
messagebox  "donate to pilight at http://www.pilight.org/"

messagebox "Add Repository apt.pilight.org and key"
addAptRepository "deb http://apt.pilight.org/ stable main" "http://apt.pilight.org/pilight.key"

messagebox "Update APT-GET sources"
apt-get update

messagebox "Install piglight"
installer pilight
