#!/bin/bash
installer supervisor
cat <<\EOF > /etc/supervisor/conf.d/pilightCommand.conf
[program:pilightCommand]
command=/opt/piget/pilightCommand/pilightCommand
autostart=true
autorestart=true
stdout_logfile=/var/log/pilightCommand.log
redirect_stderr=true
EOF
supervisorctl reread
supervisorctl update

mkdir /opt/user/config/pilight
if [ -z "/boot/piget/config/pilight/pilightCommand.cfg" ];then
	cp /boot/piget/config/pilight/pilightCommand.cfg /opt/user/config/pilight/pilightCommand.cfg
else
	cp /opt/piget/pilightCommand/default/pilightCommand.cfg /opt/user/config/pilight/pilightCommand.cfg
fi
