#!/bin/bash
installer supervisor
cat <<\EOF > /etc/supervisor/conf.d/radio433Triggers.conf
command=/opt/piget/radio433Triggers/radio433Triggers
autostart=true
autorestart=true
stdout_logfile=/var/log/radio433Triggers.log
redirect_stderr=true
EOF
supervisorctl reread
supervisorctl update


